"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['AutoZoom.py']
APP_NAME = 'AutoZoom'
DATA_FILES = ['realZoom.sh','zoom.sh']
OPTIONS = {'iconfile': 'autoZoomIcon.icns',
			'plist': {
			        'CFBundleName': APP_NAME,
			        'CFBundleDisplayName': APP_NAME,
			        'CFBundleGetInfoString': "Schedule Zoom Meetings",
			        'CFBundleIdentifier': "com.tatewalker.osx.autozoom",
			        'CFBundleVersion': "1.3.0",
			        'CFBundleShortVersionString': "1.3.0",
			        'NSRequiresAquaSystemAppearance':'false',
			        'NSHumanReadableCopyright': u"Copyright © 2020, Tate Walker, All Rights Reserved"
			    }
		}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
